# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

bases:
  - ../../base

resources:
  - namespace.yml

patchesStrategicMerge:
  - patch-server-deployment.yml
