---

apiVersion: v1
kind: Secret
metadata:
  name: ftp-secret
type: Opaque
data:
  MONDIAL_RELAY_FTP_PASSWORD: RmoydyNqZGtiMQ==
  COLISSIMO_FTP_PASSWORD: MFQ0RzFPM00=
  MONDIAL_RELAY_BE_FTP_PASSWORD: SSFwSDBqUkVjUw==