# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments.yml
  - services.yml
  - ftp-config.yml
  - ftp-secret.yml
  - db-services-config.yml
  - db-services-secret.yml
  - others-config.yml
